import java.util.Scanner;
public class Exception {
	public static void main(String[] args) {
		Scanner sc= new Scanner(System.in);
		try {
			System.out.println("Enter size of array: ");
			int size =Integer.parseInt(sc.nextLine());
			if(size<=0) {
				System.out.println("Array size must be positive");
				return;
			}
			int arr[]=new int[size];
			System.out.println("Enter the elements of the array");
			for(int i=0;i<size;i++) {
				System.out.println("Element"+i+":");
				arr[i]=Integer.parseInt( sc.nextLine());
			}
				System.out.println("Enter the index to retrive an element: ");
				int index=Integer.parseInt( sc.nextLine());
				int element = arr[index];
				System.out.println("Element at index"+index+":"+element);
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println(e.getMessage());
			System.out.println("ArrayIndexOutOfBoundsException : Index is out of range");
		}
		catch(NumberFormatException e) {
			System.out.println(e.getMessage());
			System.out.println("NumberFormatException : Please enter valid number");
		}
		finally {
			sc.close();
		}
	}
}
